version: '2'

services:

    main:
        image: alpine

    backup:
        image: loomchild/volume-backup:latest
        volumes:
            - volume:/volume
            - backup:/backup
        command: ["backup", "${ARCHIVE}"]

    restore:
        image: loomchild/volume-backup:latest
        volumes:
            - volume:/volume
            - backup:/backup
        command: ["restore", "${ARCHIVE}"]

    list:
        image: alpine
        volumes:
            - backup:/backup
        # sleep is needed due to bug in docker-compose - https://github.com/docker/compose/pull/4738
        command: ["sh", "-c", "sleep 0.2; ls -1 --color=never /backup/${ARCHIVE} 2>/dev/null"]

volumes:
    volume:
        external:
            name: ${VOLUME}
    backup:
        external:
            name: ${BACKUP}

